name: Merge PRList
description: List all open PRs in any repo
author: ekaradzha <ekaradzhaqb@quickbase.com>
inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true
  repository:
    description: 'github repository'
    required: true
    default: '${{ github.repository }}'
  state:
    description: 'filter by state of the pull request'
    required: true
    default: 'accepted'
outputs:
  pulls:
    description: 'number of pull requests'
runs:
  using: "composite"
    steps:
      #-------------------------------------#
      #  Check out repo and set up Python   #
      #-------------------------------------#
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.8
          poetry-version: 1.2.2

      #------------------------#
      #  Run your actual job   #
      #------------------------#
      - name: Run tests
        run: |
          poetry run pytest
branding:
  icon: flag
  color: gray-dark


