name: Merge PRList
description: List all open PRs in any repo
author: ekaradzha <ekaradzhaqb@quickbase.com>
inputs:
  gh_token:
    description: GitHub token
    required: true
  gh_repo:
    description: 'GitHub repository'
    required: true
    default: '${{ github.repository }}'
  gh_pr_state:
    description: 'Filter PRs by state of the pull request'
    required: true
    default: 'accepted'
outputs:
  pulls:
    description: 'number of pull requests'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ekaradzha-qb/merge-freeze
        sparse-checkout: |
          prlist.py 
          requirements.txt
        sparse-checkout-cone-mode: false
    
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
    
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    
    - name: Install dependencies
      shell: bash
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: execute py script      
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        GH_REPO: ${{ inputs.gh_repo }}
        GH_PR_STATE: ${{inputs.gh_pr_state}}
      run: |
        ls
        python prlist.py
branding:
  icon: flag
  color: gray-dark


